version: 0.2
phases:
  install:
    commands:
      - "npm install --unsafe-perm=true"
  build:
    commands:
      - "npm run build"
artifacts:
  type: zip
  files:
    - package.json
    - "dist/**/*"
    - README.md
