version: 0.2
phases:
  install:
    commands:
      - "sudo npm install --unsafe-perm"
  build:
    commands:
      - "npm run build"
artifacts:
  type: zip
  files:
    - package.json
    - "dist/**/*"
    - README.md
